In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("datatraining.txt")
data

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
1,2015-02-04 17:51:00,23.180000,27.272000,426.0,721.250000,0.004793,1
2,2015-02-04 17:51:59,23.150000,27.267500,429.5,714.000000,0.004783,1
3,2015-02-04 17:53:00,23.150000,27.245000,426.0,713.500000,0.004779,1
4,2015-02-04 17:54:00,23.150000,27.200000,426.0,708.250000,0.004772,1
5,2015-02-04 17:55:00,23.100000,27.200000,426.0,704.500000,0.004757,1
6,2015-02-04 17:55:59,23.100000,27.200000,419.0,701.000000,0.004757,1
7,2015-02-04 17:57:00,23.100000,27.200000,419.0,701.666667,0.004757,1
8,2015-02-04 17:57:59,23.100000,27.200000,419.0,699.000000,0.004757,1
9,2015-02-04 17:58:59,23.100000,27.200000,419.0,689.333333,0.004757,1
10,2015-02-04 18:00:00,23.075000,27.175000,419.0,688.000000,0.004745,1
11,2015-02-04 18:01:00,23.075000,27.150000,419.0,690.250000,0.004741,1
12,2015-02-04 18:02:00,23.100000,27.100000,419.0,691.000000,0.004739,1
13,2015-02-04 18:03:00,23.100000,27.166667,419.0,683.500000,0.004751,1
14,2015-02-04 18:04:00,23.050000,27.150000,419.0,687.500000,0.004734,1
15,2015-02-04 18:04:59,23.000000,27.125000,419.0,686.000000,0.004715,1
16,2015-02-04 18:06:00,23.000000,27.125000,418.5,680.500000,0.004715,1
17,2015-02-04 18:07:00,23.000000,27.200000,0.0,681.500000,0.004728,0
18,2015-02-04 18:08:00,22.945000,27.290000,0.0,685.000000,0.004728,0
19,2015-02-04 18:08:59,22.945000,27.390000,0.0,685.000000,0.004745,0
20,2015-02-04 18:10:00,22.890000,27.390000,0.0,689.000000,0.004730,0
21,2015-02-04 18:10:59,22.890000,27.390000,0.0,689.500000,0.004730,0
22,2015-02-04 18:11:59,22.890000,27.390000,0.0,689.000000,0.004730,0
23,2015-02-04 18:13:00,22.890000,27.445000,0.0,691.000000,0.004739,0
24,2015-02-04 18:14:00,22.890000,27.500000,0.0,688.000000,0.004749,0
25,2015-02-04 18:15:00,22.890000,27.500000,0.0,689.500000,0.004749,0
26,2015-02-04 18:16:00,22.790000,27.445000,0.0,689.000000,0.004710,0
27,2015-02-04 18:16:59,22.790000,27.500000,0.0,685.666667,0.004720,0
28,2015-02-04 18:17:59,22.790000,27.500000,0.0,687.000000,0.004720,0
29,2015-02-04 18:19:00,22.790000,27.500000,0.0,688.000000,0.004720,0
30,2015-02-04 18:20:00,22.745000,27.500000,0.0,670.000000,0.004707,0
...,...,...,...,...,...,...,...
8114,2015-02-10 09:04:00,20.700000,34.417500,419.0,568.750000,0.005203,1
8115,2015-02-10 09:04:59,20.700000,34.090000,419.0,556.666667,0.005153,1
8116,2015-02-10 09:06:00,20.700000,34.296667,419.0,548.000000,0.005184,1
8117,2015-02-10 09:07:00,20.730000,34.466667,419.0,563.333333,0.005220,1
8118,2015-02-10 09:08:00,20.745000,34.567500,426.0,593.750000,0.005240,1
8119,2015-02-10 09:08:59,20.767500,34.717500,422.5,600.750000,0.005270,1
8120,2015-02-10 09:10:00,20.790000,35.090000,426.0,623.000000,0.005335,1
8121,2015-02-10 09:10:59,20.790000,34.972500,433.0,631.000000,0.005317,1
8122,2015-02-10 09:11:59,20.790000,34.826667,433.0,636.000000,0.005295,1
8123,2015-02-10 09:13:00,20.840000,35.195000,433.0,636.750000,0.005368,1
8124,2015-02-10 09:14:00,20.890000,35.300000,433.0,663.000000,0.005401,1
8125,2015-02-10 09:15:00,20.856667,35.096667,433.0,665.333333,0.005358,1
8126,2015-02-10 09:16:00,20.890000,35.320000,433.0,669.500000,0.005404,1
8127,2015-02-10 09:16:59,20.917500,35.475000,433.0,679.250000,0.005437,1
8128,2015-02-10 09:17:59,20.890000,35.400000,433.0,684.666667,0.005416,1
8129,2015-02-10 09:19:00,20.917500,35.717500,433.0,706.250000,0.005474,1
8130,2015-02-10 09:20:00,20.958750,35.683750,433.0,712.625000,0.005483,1
8131,2015-02-10 09:21:00,21.000000,35.650000,433.0,719.000000,0.005492,1
8132,2015-02-10 09:22:00,21.000000,35.700000,433.0,730.250000,0.005500,1
8133,2015-02-10 09:23:00,21.000000,35.760000,433.0,739.000000,0.005509,1
8134,2015-02-10 09:23:59,21.000000,35.850000,433.0,756.250000,0.005523,1
8135,2015-02-10 09:24:59,21.000000,35.700000,433.0,761.000000,0.005500,1
8136,2015-02-10 09:26:00,21.025000,35.950000,433.0,763.000000,0.005547,1
8137,2015-02-10 09:27:00,21.000000,35.860000,433.0,771.333333,0.005525,1
8138,2015-02-10 09:28:00,21.050000,36.050000,433.0,780.250000,0.005571,1
8139,2015-02-10 09:29:00,21.050000,36.097500,433.0,787.250000,0.005579,1
8140,2015-02-10 09:29:59,21.050000,35.995000,433.0,789.500000,0.005563,1
8141,2015-02-10 09:30:59,21.100000,36.095000,433.0,798.500000,0.005596,1
8142,2015-02-10 09:32:00,21.100000,36.260000,433.0,820.333333,0.005621,1
8143,2015-02-10 09:33:00,21.100000,36.200000,447.0,821.000000,0.005612,1

In [3]:
data = data.drop("date",axis = 1)

In [4]:
data

      Temperature   Humidity  Light         CO2  HumidityRatio  Occupancy
1       23.180000  27.272000  426.0  721.250000       0.004793          1
2       23.150000  27.267500  429.5  714.000000       0.004783          1
3       23.150000  27.245000  426.0  713.500000       0.004779          1
4       23.150000  27.200000  426.0  708.250000       0.004772          1
5       23.100000  27.200000  426.0  704.500000       0.004757          1
6       23.100000  27.200000  419.0  701.000000       0.004757          1
7       23.100000  27.200000  419.0  701.666667       0.004757          1
8       23.100000  27.200000  419.0  699.000000       0.004757          1
9       23.100000  27.200000  419.0  689.333333       0.004757          1
10      23.075000  27.175000  419.0  688.000000       0.004745          1
11      23.075000  27.150000  419.0  690.250000       0.004741          1
12      23.100000  27.100000  419.0  691.000000       0.004739          1
13      23.100000  27.166667  419.0  683.500000       0.004751          1
14      23.050000  27.150000  419.0  687.500000       0.004734          1
15      23.000000  27.125000  419.0  686.000000       0.004715          1
16      23.000000  27.125000  418.5  680.500000       0.004715          1
17      23.000000  27.200000    0.0  681.500000       0.004728          0
18      22.945000  27.290000    0.0  685.000000       0.004728          0
19      22.945000  27.390000    0.0  685.000000       0.004745          0
20      22.890000  27.390000    0.0  689.000000       0.004730          0
21      22.890000  27.390000    0.0  689.500000       0.004730          0
22      22.890000  27.390000    0.0  689.000000       0.004730          0
23      22.890000  27.445000    0.0  691.000000       0.004739          0
24      22.890000  27.500000    0.0  688.000000       0.004749          0
25      22.890000  27.500000    0.0  689.500000       0.004749          0
26      22.790000  27.445000    0.0  689.000000       0.004710          0
27      22.790000  27.500000    0.0  685.666667       0.004720          0
28      22.790000  27.500000    0.0  687.000000       0.004720          0
29      22.790000  27.500000    0.0  688.000000       0.004720          0
30      22.745000  27.500000    0.0  670.000000       0.004707          0
...           ...        ...    ...         ...            ...        ...
8114    20.700000  34.417500  419.0  568.750000       0.005203          1
8115    20.700000  34.090000  419.0  556.666667       0.005153          1
8116    20.700000  34.296667  419.0  548.000000       0.005184          1
8117    20.730000  34.466667  419.0  563.333333       0.005220          1
8118    20.745000  34.567500  426.0  593.750000       0.005240          1
8119    20.767500  34.717500  422.5  600.750000       0.005270          1
8120    20.790000  35.090000  426.0  623.000000       0.005335          1
8121    20.790000  34.972500  433.0  631.000000       0.005317          1
8122    20.790000  34.826667  433.0  636.000000       0.005295          1
8123    20.840000  35.195000  433.0  636.750000       0.005368          1
8124    20.890000  35.300000  433.0  663.000000       0.005401          1
8125    20.856667  35.096667  433.0  665.333333       0.005358          1
8126    20.890000  35.320000  433.0  669.500000       0.005404          1
8127    20.917500  35.475000  433.0  679.250000       0.005437          1
8128    20.890000  35.400000  433.0  684.666667       0.005416          1
8129    20.917500  35.717500  433.0  706.250000       0.005474          1
8130    20.958750  35.683750  433.0  712.625000       0.005483          1
8131    21.000000  35.650000  433.0  719.000000       0.005492          1
8132    21.000000  35.700000  433.0  730.250000       0.005500          1
8133    21.000000  35.760000  433.0  739.000000       0.005509          1
8134    21.000000  35.850000  433.0  756.250000       0.005523          1
8135    21.000000  35.700000  433.0  761.000000       0.005500          1
8136    21.025000  35.950000  433.0  763.000000       0.005547          1
8137    21.000000  35.860000  433.0  771.333333       0.005525          1
8138    21.050000  36.050000  433.0  780.250000       0.005571          1
8139    21.050000  36.097500  433.0  787.250000       0.005579          1
8140    21.050000  35.995000  433.0  789.500000       0.005563          1
8141    21.100000  36.095000  433.0  798.500000       0.005596          1
8142    21.100000  36.260000  433.0  820.333333       0.005621          1
8143    21.100000  36.200000  447.0  821.000000       0.005612          1

[8143 rows x 6 columns]

In [7]:
data.to_csv("data-new.csv",index = False)